name: Make Release Builds

on: [push, workflow_dispatch]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          {submodules: 'recursive'}
      - name: Get artifact name
        run: echo "ARTIFACT_NAME=$(python3 build.py --print-artifact-name)" >> $GITHUB_ENV
      - run: python3 build.py --dependencies
      - run: python3 build.py --configure
      - run: python3 build.py --build
      - run: python3 build.py --package
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ~/work/OttoMatic/OttoMatic/dist/OttoMatic-4.0.2-mac.dmg
  
  cd_upload_artifacts_to_release:
    name: Upload
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs:
      - build-macos
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: true
      - name: Install github-release
        run: |
          go install github.com/github-release/github-release@latest
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Set environment variables
        run: |
          echo "GITHUB_USER=$( echo ${{ github.repository }} | cut -d/ -f1 )" >> $GITHUB_ENV
          echo "GITHUB_REPO=$( echo ${{ github.repository }} | cut -d/ -f2 )" >> $GITHUB_ENV
      - name: Move/Create continuous tag
        run: |
          git tag --force continuous ${{ github.sha }}
          git push --tags --force
      - name: Setup continuous release
        run: |
          DESCRIPTION="Triggered on $(date -u '+%Y/%m/%d, %H:%M') UTC by commit ${{ github.sha }} (@${{ github.actor }})

          This is an ottomated build of the latest source. Use with caution!

          https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          if ! github-release info -t continuous > /dev/null 2>&1; then
            github-release release \
              --tag continuous \
              --name "Continuous Build" \
              --description "$DESCRIPTION" \
              --pre-release
          else
            github-release edit \
              --tag continuous \
              --name "Continuous Build" \
              --description "$DESCRIPTION" \
              --pre-release
          fi
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: OttoMatic-4.0.2-mac.dmg
      - name: Add build to release tag
        continue-on-error: true
        run: |
          github-release upload \
            --tag continuous \
            --replace \
            --name ${{ env.OUTPUT }} \
            --file ${{ env.OUTPUT }}/${{ env.OUTPUT }}
